apiVersion: apps/v1
kind: Deployment
metadata:
  name: id-web-deployment
  namespace: boldbi
spec:
  selector:
    matchLabels:
      app: id-web
  replicas: 1
  template:
    metadata:
      labels:
        app: id-web
    spec:
      containers:
      - name: id-web-container
        image: gcr.io/boldbi-294612/boldbi-identity:4.1.36
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
            memory: 750Mi
        env:
        - name: APP_BASE_URL
          value: http://host.docker.internal
        - name: INSTALL_OPTIONAL_LIBS
          value: phantomjs,mongodb,mysql,influxdb,snowflake,oracle,npgsql
        readinessProbe:
          httpGet:
            path: /health-check
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        volumeMounts:
        - mountPath: /boldbi/app_data
          name: id-web-volume
      volumes:
      - name: id-web-volume
        persistentVolumeClaim:
          claimName: boldbi-fileserver-claim
          readOnly: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: id-api-deployment
  namespace: boldbi
spec:
  selector:
    matchLabels:
      app: id-api
  replicas: 1
  template:
    metadata:
      labels:
        app: id-api
    spec:
      containers:
      - name: id-api-container
        image: gcr.io/boldbi-294612/boldbi-identity-api:4.1.36
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
            memory: 750Mi
        readinessProbe:
          httpGet:
            path: /health-check
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 10
        volumeMounts:
        - mountPath: /boldbi/app_data
          name: id-api-volume
      volumes:
      - name: id-api-volume
        persistentVolumeClaim:
          claimName: boldbi-fileserver-claim
          readOnly: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: id-ums-deployment
  namespace: boldbi
spec:
  selector:
    matchLabels:
      app: id-ums
  replicas: 1
  template:
    metadata:
      labels:
        app: id-ums
    spec:
      containers:
      - name: id-ums-container
        image: gcr.io/boldbi-294612/boldbi-ums:4.1.36
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
            memory: 750Mi
        readinessProbe:
          httpGet:
            path: /health-check
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 10
        volumeMounts:
        - mountPath: /boldbi/app_data
          name: id-ums-volume
      volumes:
      - name: id-ums-volume
        persistentVolumeClaim:
          claimName: boldbi-fileserver-claim
          readOnly: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bi-web-deployment
  namespace: boldbi
spec:
  selector:
    matchLabels:
      app: bi-web
  replicas: 1
  template:
    metadata:
      labels:
        app: bi-web
    spec:
      containers:
      - name: bi-web-container
        image: gcr.io/boldbi-294612/boldbi-server:4.1.36
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
            memory: 750Mi
        readinessProbe:
          httpGet:
            path: /health-check
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 10
        volumeMounts:
        - mountPath: /boldbi/app_data
          name: bi-web-volume
      volumes:
      - name: bi-web-volume
        persistentVolumeClaim:
          claimName: boldbi-fileserver-claim
          readOnly: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bi-api-deployment
  namespace: boldbi
spec:
  selector:
    matchLabels:
      app: bi-api
  replicas: 1
  template:
    metadata:
      labels:
        app: bi-api
    spec:
      containers:
      - name: bi-api-container
        image: gcr.io/boldbi-294612/boldbi-server-api:4.1.36
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
            memory: 750Mi
        readinessProbe:
          httpGet:
            path: /health-check
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 10
        volumeMounts:
        - mountPath: /boldbi/app_data
          name: bi-api-volume
      volumes:
      - name: bi-api-volume
        persistentVolumeClaim:
          claimName: boldbi-fileserver-claim
          readOnly: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bi-jobs-deployment
  namespace: boldbi
spec:
  selector:
    matchLabels:
      app: bi-jobs
  replicas: 1
  template:
    metadata:
      labels:
        app: bi-jobs
    spec:
      containers:
      - name: bi-jobs-container
        image: gcr.io/boldbi-294612/boldbi-server-jobs:4.1.36
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
            memory: 750Mi
        readinessProbe:
          httpGet:
            path: /health-check
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 10
        volumeMounts:
        - mountPath: /boldbi/app_data
          name: bi-jobs-volume
      volumes:
      - name: bi-jobs-volume
        persistentVolumeClaim:
          claimName: boldbi-fileserver-claim
          readOnly: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bi-dataservice-deployment
  namespace: boldbi
spec:
  selector:
    matchLabels:
      app: bi-dataservice
  replicas: 1
  template:
    metadata:
      labels:
        app: bi-dataservice
    spec:
      containers:
      - name: bi-dataservice-container
        image: gcr.io/boldbi-294612/boldbi-designer:4.1.36
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
            memory: 750Mi
        readinessProbe:
          httpGet:
            path: /health-check
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 10
        volumeMounts:
        - mountPath: /boldbi/app_data
          name: bi-dataservice-volume
      volumes:
      - name: bi-dataservice-volume
        persistentVolumeClaim:
          claimName: boldbi-fileserver-claim
          readOnly: false