apiVersion: v1
kind: PersistentVolume
metadata:
 name: boldbi-fileserver
 namespace: boldbi
spec:
 capacity:
   storage: 3Gi
 accessModes:
 - ReadWriteMany
 nfs:
   path: /<file_share_name>
   server: <file_share_ip_address>
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: boldbi-fileserver-claim
 namespace: boldbi
spec:
 accessModes:
 - ReadWriteMany
 storageClassName: ""
 volumeName: boldbi-fileserver
 resources:
   requests:
     storage: 3Gi