apiVersion: v1
kind: Secret
metadata:
  name: boldbi-azure-secret
  namespace: boldbi
type: Opaque
data:
  azurestorageaccountname: <base64_azurestorageaccountname>
  azurestorageaccountkey: <base64_azurestorageaccountkey>
---
apiVersion: v1
kind: PersistentVolume
metadata:
 name: boldbi-fileserver
 namespace: boldbi
spec:
 capacity:
   storage: 3Gi
 accessModes:
 - ReadWriteMany
 persistentVolumeReclaimPolicy: Retain
 storageClassName: azurefile
 azureFile:
   secretName: boldbi-azure-secret
   shareName: <file_share_name>
   readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: boldbi-fileserver-claim
 namespace: boldbi
spec:
 accessModes:
 - ReadWriteMany
 storageClassName: azurefile
 volumeName: boldbi-fileserver
 resources:
   requests:
     storage: 3Gi