kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc
  namespace: boldbi
provisioner: efs.csi.aws.com
---
apiVersion: v1
kind: PersistentVolume
metadata:
 name: boldbi-fileserver
 namespace: boldbi
spec:
 capacity:
   storage: 3Gi
 accessModes:
 - ReadWriteMany
 persistentVolumeReclaimPolicy: Retain
 storageClassName: efs-sc
 csi:
   driver: efs.csi.aws.com
   volumeHandle: <efs_file_system_id>
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: boldbi-fileserver-claim
 namespace: boldbi
spec:
 accessModes:
 - ReadWriteMany
 storageClassName: efs-sc
 volumeName: boldbi-fileserver
 resources:
   requests:
     storage: 3Gi